apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: result-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kaushalyasithumini29/backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: mongodb://mongo:27017/result-management
