apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: result-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: sithumini1215
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: FbP2QL5oEMkjN4wD
        - name: MONGO_INITDB_DATABASE
          value: result-management
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
